added some other bash lines

diff --git a/.github/workflows/06-deploy_and_test.yaml b/.github/workflows/06-deploy_and_test.yaml
--- a/.github/workflows/06-deploy_and_test.yaml
+++ b/.github/workflows/06-deploy_and_test.yaml
@@ -43,6 +43,18 @@ jobs:
     - name: run pipeline
       run: |
           run_id=$(az ml job create --file src/production_job.yml --resource-group Learn_MLOps --workspace-name mlops_ws_prod --query name -o tsv)
+          if [[ -z "$run_id" ]]
+          then
+            echo "Job creation failed"
+            exit 3
+          fi
+          az ml job show -n $run_id --web
+          status=$(az ml job show -n $run_id --query status -o tsv)
+          if [[ -z "$status" ]]
+          then
+            echo "Status query failed"
+            exit 4
+          fi
 
   create-endpoint:
     needs: production
